pipeline {
	agent {docker { image 'python:3.13.7-alpine3.22' }}
	stages {
		stage('Setup') {
			steps {
			    sh '''
			    python -m venv venv
			    . venv/bin/activate 
			    pip install -r requirements.txt
			    '''
			}
		}
	}
}

